# Generated by Django 3.2.6 on 2021-08-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('educator', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sub_description', models.CharField(max_length=300)),
                ('num_lesson', models.PositiveSmallIntegerField(default=0)),
                ('picture', models.ImageField(upload_to='course_picture')),
            ],
        ),
    ]
